export const LOGIN = 'LOGIN';
export const IS_LOGGED = 'IS_LOGGED';
export const LOGIN_HAS_ERROR = 'LOGIN_HAS_ERROR';

export const SIGNUP = 'SIGNUP';
export const IS_SIGNUP = 'IS_SIGNUP';
export const SIGNUP_HAS_ERROR = 'SIGNUP_HAS_ERROR';

export const FORGETPASS = 'FORGETPASS';
export const IS_FORGETPASS = 'IS_FORGETPASS';
export const FORGETPASS_HAS_ERROR = 'FORGETPASS_HAS_ERROR';

export const RESETPASS = 'RESETPASS';
export const IS_RESETPASS = 'IS_RESETPASS';
export const RESETPASS_HAS_ERROR = 'RESETPASS_HAS_ERROR';

export const DRAWERMENU = 'DRAWERMENU';
export const IS_DRAWERMENU = 'IS_DRAWERMENU';
export const DRAWERMENU_HAS_ERROR = 'DRAWERMENU_HAS_ERROR';


export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const IS_UPLOAD_IMAGE = 'IS_UPLOAD_IMAGE';
export const UPLOAD_IMAGE_HAS_ERROR = 'UPLOAD_IMAGE_HAS_ERROR';


export const SIDESCREEN = 'SIDESCREEN';
export const IS_SIDESCREEN = 'IS_SIDESCREEN';
export const SIDESCREEN_HAS_ERROR = 'SIDESCREEN_HAS_ERROR';

export const UPDATEPROFILE = 'UPDATEPROFILE';
export const IS_UPDATEPROFILE = 'IS_UPDATEPROFILE';
export const UPDATEPROFILE_HAS_ERROR = 'UPDATEPROFILE_HAS_ERROR';

export const MEETPEOPLE = 'MEETPEOPLE';
export const IS_MEETPEOPLE = 'IS_MEETPEOPLE';
export const MEETPEOPLE_HAS_ERROR = 'MEETPEOPLE_HAS_ERROR';

export const USERPROFILE = 'USERPROFILE';
export const IS_USERPROFILE= 'IS_USERPROFILE';
export const USERPROFILE_HAS_ERROR = 'USERPROFILE_HAS_ERROR';

export const ALLEVENTS = 'ALLEVENTS';
export const IS_ALLEVENTS = 'IS_ALLEVENTS';
export const ALLEVENTS_HAS_ERROR = 'ALLEVENTS_HAS_ERROR';

export const CREATESPONSER = 'CREATESPONSER';
export const IS_CREATESPONSER = 'IS_CREATESPONSER';
export const CREATESPONSER_HAS_ERROR = 'CREATESPONSER_HAS_ERROR';
