const font = {
    FONT_ROBOTO_BLACK: 'Roboto-Black',
    FONT_ROBOTO_BLACK_ITALIC: 'Roboto-BlackItalic',
    FONT_ROBOTO_BOLD: 'Roboto-Bold',
    FONT_ROBOTO_BOLD_ITALIC: 'Roboto-BoldItalic',
    FONT_ROBOTO_ITALIC: 'Roboto-Italic',
    FONT_ROBOTO_LIGHT: 'Roboto-Light',
    FONT_ROBOTO_LIGHT_ITALIC: 'Roboto-LightItalic',
    FONT_ROBOTO_MEDIUM: 'Roboto-Medium',
    FONT_ROBOTO_MEDIUM_ITALIC: 'Roboto-MediumItalic',
    FONT_ROBOTO_REGULAR: 'Roboto-Regular',
    FONT_ROBOTO_THIN: 'Roboto-Thin',
    FONT_ROBOTO_THIN_ITALIC: 'Roboto-ThinItalic',
  
    FONT_BLACK: 'Poppins-Black',
    FONT_BLACK_ITALIC: 'Poppins-BlackItalic',
    FONT_BOLD: 'Poppins-Bold',
    FONT_BOLD_ITALIC: 'Poppins-BoldItalic',
    FONT_EXTRA_BOLD: 'Poppins-ExtraBold',
    FONT_EXTRA_BOLD_ITALIC: 'Poppins-ExtraBoldItalic',
    FONT_EXTRA_LIGHT: 'Poppins-ExtraLight',
    FONT_EXTRA_LIGHT_ITALIC: 'Poppins-ExtraLightItalic',
    FONT_ITALIC: 'Poppins-Italic',
    FONT_LIGHT: 'Poppins-Light',
    FONT_LIGHT_ITALIC: 'Poppins-LightItalic',
    FONT_MEDIUM: 'Poppins-Medium',
    FONT_MEDIUM_ITALIC: 'Poppins-MediumItalic',
    FONT_REGULAR: 'Poppins-Regular',
    FONT_SEMI_BOLD: 'Poppins-SemiBold',
    FONT_SEMI_BOLD_ITALIC: 'Poppins-SemiBoldItalic',
    FONT_THINM: 'Poppins-Thin',
    FONT_THIM_ITALIC: 'Poppins-ThinItalic',
  }
  
  export default font;