import { StyleSheet } from "react-native";
import { w, h } from "../../utils/Dimensions";
import fonts from "../../theme/fonts";
import { Right } from "native-base";
export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#f7f6fb",
  },
  headerView: {
    alignItems: "center",
  },
  headerImage: {
    height: h(20),
    width: w(100),
    resizeMode: "cover",
    alignSelf: "center",
  },
  edit: {
    color: "#f7f6fb",
    height: h(3.5),
    width: h(3.5),
    resizeMode: "contain",
  },
  headingText: {
    color: "#fff",
    fontSize: h(3),
    marginTop: Platform.OS === "ios" ? h(-4) : h(-4),
    //: fonts.semiBold,
    alignSelf: "center",
    alignItems: "center",
    fontWeight: "bold",
  },
  university: {
    color: "#000",
    fontSize: h(2),
    fontWeight: "700",
    //: fonts.regularText,
    padding: h(1),
    opacity: 0.5,
  },

  infoIcon: {
    tintColor: "#fff",
    height: h(3.5),
    width: h(3.5),
    alignItems: "center",
    alignSelf: "center",
    // marginLeft: h(1)
  },
  LocIcon: {
     tintColor: "gray",
    height: h(3.5),
    width: h(3.5),
    alignItems: "center",
    alignSelf: "center",
    //  marginLeft: h(-1),
  },
  contactIcon:{
    tintColor: "grey",
    height: h(2.3),
    width: h(2.3),
    alignItems: "center",
    alignSelf: "center",
    marginLeft: h(.5),
  },
  semiBoldText: {
    color: "#fff",
    fontSize: h(2.5),
    //: fonts.semiBold,
    marginHorizontal: h(5),
    fontWeight: "bold",
  },
  paragraph: {
    color: "#000",
    fontSize: h(1.9),
    //: fonts.regularText,
    marginTop: h(1),
    marginBottom: h(2),
    opacity: 0.5,
  },
  cardView1: {
    marginTop: h(-8),
    padding: h(1.5),
    //  height: h(59),
    width: w(90),
    alignSelf: "center",
    borderRadius: h(3),
    borderColor: "#ddd",
    elevation: 5,
    backgroundColor: "#fff",
    marginHorizontal: h(2),
    marginBottom: h(2),
  },

  semiBoldText: {
    color: "#000",
    fontSize: h(2),
    //: fonts.semiBold,
  },
  isha: {
    color: "#df396b",
    fontSize: h(2.5),
    alignSelf: "center",
    //: fonts.semiBold,
  },
  cardView: {
    padding: h(2),
    width: w(95),
    alignSelf: "center",
    borderBottomLeftRadius: h(3),
    borderBottomRightRadius: h(3),
    borderColor: "#ddd",
    elevation: 5,
    backgroundColor: "#fff",
  },
  lightText: {
    color: "gray",
    fontSize: h(1.7),
    //: fonts.lightText,
  },
  normalText: {
    color: "#000",
    fontSize: h(1.9),
    //: fonts.regularText,
    alignSelf: "center",
  },
  hostImage: {
    height: h(3.5),
    width: h(3.5),
    borderRadius: h(3.5 / 2),
    marginHorizontal: h(1),
    alignItems: "center",
    alignSelf: "center",
  },
  userNameText: {
    color: "#df396b",
    fontSize: h(1.9),
    //: fonts.regularText,
    alignSelf: "center",
  },
  locationIcon: {
    height: h(3.5),
    width: h(3.5),
    alignSelf: "center",
  },
  onMapText: {
    color: "#df396b",
    fontSize: h(1.9),
    //: fonts.semiBold,
    alignSelf: "center",
  },
  cardDetailView: {
    padding: h(1),
    height: h(11.5),
    marginVertical: h(1),
    borderRadius: 15,
    borderColor: "#ddd",
    elevation: 10,
    backgroundColor: "#f7f6fb",
  },
  timeLightText: {
    color: "gray",
    fontSize: h(1.6),
    //: fonts.lightText,
  },
  CashText: {
    color: "#000",
    fontSize: h(3.3),
    //: fonts.bold,
    marginVertical: h(1),
  },
  TagsView: {
    color: "#000",
    fontSize: h(2),
    //: fonts.semiBold,
    padding: h(2),
  },
  EventbtnView: {
    backgroundColor: "#df396b",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    height: h(5),
    minWidth: "30%",
    borderColor: "#ddd",
    elevation: 5,
    marginRight: h(2),
    marginVertical: h(1),
  },
  EventbtnTextStyle: {
    color: "#fff",
    fontSize: h(2),
    //: fonts.regularText,
    alignSelf: "center",
  },
  desText: {
    color: "gray",
    fontSize: h(1.7),
    //: fonts.lightText,
    marginHorizontal: h(2),
    marginTop: h(-1.5),
  },
  ReservebtnView: {
    backgroundColor: "#df396b",
    borderRadius: 20,
    alignSelf: "center",
    justifyContent: "center",
    height: h(8),
    width: w(94),
    marginHorizontal: h(1),
    marginVertical: h(2),
    borderColor: "#ddd",
    elevation: 5,
  },
  ReservebtnTextStyle: {
    color: "#fff",
    fontSize: h(2.2),
    //: fonts.semiBold,
    alignSelf: "center",
  },
  photoImage: {
    //  margin:h(5),
    height: h(10),
    width: h(10),
    borderWidth: h(0.2),
    borderColor: "#cecece",
    borderRadius: h(2),
  },
  photoImage2: {
    height: h(18),
    width: h(18),
    borderRadius: h(2),
    marginRight: h(2),
  },
  camera: {
    height: h(4.5),
    width: h(4.5),
    resizeMode: "contain",
    alignSelf: "flex-end",
  },
  expand: {
    height: h(10),
    width: w(15),
    resizeMode: "cover",
    marginHorizontal: h(40),
    marginTop: -33,
  },
  semiBoldText1: {
    color: "#000",
    fontSize: h(2),
    //: fonts.semiBold,
    fontWeight: "700",
  },
  interestbubble:{
    marginTop:h(.5),
    marginBottom:h(.5),
    padding:h(1),
    backgroundColor: '#df396b',
    borderRadius: h(3),
    alignSelf: 'flex-start',
    // height: h(4),
    minWidth:h(10),
    borderColor: '#ddd',
    elevation: 5,
    marginRight:h(2)
  },
  bubbleText:{
    color: '#fff',
    fontSize: h(1.8),
    //: fonts.bold,
    alignSelf:'center',
    top:-2
  }
});
